package com.tmtp.web.TMTP.service;

import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;

@Service
public class CommentFilteringServiceImpl implements CommentFilteringService {

    private List<String> abusiveTerms = Arrays.asList("nigger",
                                                        "nigga",
                                                        "neger",
                                                        "paki",
                                                        "chinky",
                                                        "chinaman",
                                                        "chink",
                                                        "faggot",
                                                        "fag",
                                                        "faggit",
                                                        "slut",
                                                        "sloot",
                                                        "negro",
                                                        "negros",
                                                        "niggas",
                                                        "niggaz",
                                                        "pikie");
// "felch",
//                                                        "cunt",
//                                                        "skullfuck",
//                                                        "cum dumpster",
//                                                        "Alabama hot pocket",
//                                                        "blumpkin",
//                                                        "rusty trombone",
//                                                        "cock-juggling thunder cunt",
//                                                        "Cleveland Steamer",
//                                                        "cuntee",
//                                                        "cum guzzling cock sucker",
//                                                        "glass bottom boat",
//                                                        "suck a fat baby dick",
//                                                        "bate",
//                                                        "meat flap",
//                                                        "fuck hole",
//                                                        "hairy axe wound",
//                                                        "cumjunkie",
//                                                        "assmucus",
//                                                        "beef curtain",
//                                                        "cumdump",
//                                                        "eat hair pie",
//                                                        "cum chugger",
//                                                        "roast beef curtains",
//                                                        "mother fucker",
//                                                        "bitchass mother fucker",
//                                                        "fucking pussy",
//                                                        "motherfucking",
//                                                        "fuck",
//                                                        "cum freak",
//                                                        "lick my froth",
//                                                        "50 yard cunt punt",
//                                                        "clitty litter",
//                                                        "fist fuck",
//                                                        "blue waffle",
//                                                        "fuck yo mama",
//                                                        "get some squish",
//                                                        "motherfucker",
//                                                        "eat a dick",
//                                                        "sausage queen",
//                                                        "tittie Christ",
//                                                        "fuckmeat",
//                                                        "facialize",
//                                                        "have a face like a hatful of assholes",
//                                                        "bang box",
//                                                        "fuck me in the ass with no Vaseline",
//                                                        "meat drapes",
//                                                        "schlong juice",
//                                                        "buggery",
//                                                        "squeeze a steamer",
//                                                        "analconda",
//                                                        "cock snot",
//                                                        "butt fuck",
//                                                        "fucktoy",
//                                                        "chota bags",
//                                                        "clit licker",
//                                                        "shit fucker",
//                                                        "fleet support unit",
//                                                        "slaptard",
//                                                        "smoke a sausage",
//                                                        "dick hole",
//                                                        "cuntsicle",
//                                                        "cock pocket",
//                                                        "cunt-struck",
//                                                        "gangbang",
//                                                        "bust a load",
//                                                        "GMILF",
//                                                        "pussy fart",
//                                                        "cum guzzler",
//                                                        "ass fuck",
//                                                        "feedbag material",
//                                                        "cunt hole",
//                                                        "baby arm",
//                                                        "dick sucker",
//                                                        "cunt face",
//                                                        "slich",
//                                                        "anal impaler",
//                                                        "got a squirrel peeking",
//                                                        "shum",
//                                                        "hemped up",
//                                                        "cuntbag",
//                                                        "cocksucker",
//                                                        "eat fur pie",
//                                                        "get brain",
//                                                        "get redwings",
//                                                        "ham flap",
//                                                        "nut butter",
//                                                        "dick",
//                                                        "suck a dick",
//                                                        "man chowder",
//                                                        "Andhra Black Cobra",
//                                                        "donkey punch",
//                                                        "fuck puppet",
//                                                        "bisnotch",
//                                                        "brown-cap",
//                                                        "hatchet wound",
//                                                        "thundercunt",
//                                                        "blow me",
//                                                        "buckle buffer",
//                                                        "have peanut butter stirred",
//                                                        "dick");
    private boolean appearance = false;

    @Override
    public boolean filterComment(String comment){
        if(abusiveTerms.stream().parallel().anyMatch(comment::contains)){
            appearance = true;
        }
        return appearance;
    }
}
