package com.tmtp.web.TMTP.entity;

public enum Team {
    ABERDEEN("Aberdeen FC"),
    ABERDEENGAY("Aberdeen Gay League FC"),
    MILAN("AC Milan"),
    FIORENTINA("ACF Fiorentina"),
    ADODENHAAG("ADO Den Haag"),
    AJAX("Ajax FC"),
    AMKARPERM("Amkar Perm"),
    ANDERLECHT("Anderlecht FC"),
    ANJI("Anji FC"),
    ANTWERP("Antwerp FC"),
    ARGENTINOSJUNIORS("Argentinos Juniors FC"),
    ARSENAL("Arsenal"),
    ROMA("AS Roma"),
    ATALANTA("Atalanta BC"),
    ATLANTA("Atlanta United FC"),
    ATLETICAPONTE("Atletica Ponte Prata"),
    ATLETICOMADRID("Atletico Madrid"),
    ATLETICOMINEIRO("Atletico Mineiro FC"),
    ATLETICOTUCUMAN("Atletico Tucuman FC"),
    AVAI("Avai FC"),
    ALKMAAR("AZ Alkmaar"),
    BARCELONA("Barcelona FC"),
    BARCELONAGAY("Barcelona Gay League FC"),
    BARNSLEY("Barnsley FC"),
    BAYERN("Bayern Munich"),
    BELGRANO("Belgrano FC"),
    BESIKTAS("Besiktas FC"),
    BIRMINGHAM("Birmingham FC"),
    BOAVISTA("BoaVista FC"),
    BOCAJUNIORS("Boca Juniors FC"),
    BOLOGNA("Bologna FC"),
    BOLTON("Bolton FC"),
    BORDEAUX("Bordeaux FC"),
    BORUSSIA("Borussia Dortmund FC"),
    BOTAFOGO("Botafogo de Futebol e Regatas"),
    BOTTOMSGAY("Bottoms Up Gay League FC"),
    BOURNEMOUTH("Bournemouth FC"),
    BRENTFORD("Brentford FC"),
    BRIGHTONHOVE("Brighton & Hove Albion FC"),
    BRISTON("Briston City FC"),
    BURSASPOR("Bursaspor FC"),
    BURTON("Burton FC"),
    BELENENSES("CF OS Belenenses"),
    MARITIMO("CS Maritimo"),
    CAGLIARI("Cagliari Calcio"),
    CELTIC("Celtic FC"),
    CHARLEROI("Charleroi FC"),
    CHELSEA("Chelsea FC"),
    CHICAGO("Chicago Fire"),
    BRUGGE("Club Brugge FC"),
    FLAMENGO("Clube de Regatas do Flamengo"),
    COLON("Colon FC"),
    COLORADO("Colorado Rapids"),
    COLUMBUS("Columbus Crew SC"),
    COMEOUTGAY("Come Out Gay League FC"),
    CORITIBA("Coritiba FC"),
    VASCODAGAMA("CR Vasco Da Gama FC"),
    CRYSTAL("Crystal Palace"),
    CSKA("CSKA Moscow"),
    DC("DC United"),
    DEFENSAJUSTICIA("Defensa y Justicia FC"),
    DERBY("Derby County FC"),
    DIJON("Dijon FCO"),
    DUNDEE("Dundee United FC"),
    DYNAMOMOSCOW("Dynamo Moscow FC"),
    FRANKFURT("Eintracht Frankfurt"),
    BAHIA("Esporte Clube Bahia"),
    PALMEIRAS("Esportiva Palmeiras"),
    ESTUDIANTES("Estudiantes FC"),
    EVERTON("Everton FC"),
    BASEL("FC Basel"),
    CROTONE("FC Crotone"),
    DALLAS("FC Dallas"),
    KOLN("FC Koln"),
    KRASNODAR("FC Krasnodar"),
    PORTO("FC Porto"),
    ROSTOV("FC Rostov"),
    SCHALKE("FC Schalke 04"),
    GALLEN("FC St Gallen"),
    THUN("FC Thun"),
    UFA("FC Ufa"),
    URAL("FC Ural"),
    UTRECHT("FC Utrecht"),
    ZURICH("FC Zurich"),
    FENERBAHCE("Fenerbahce FC"),
    FEYENOORD("Feyenoord FC"),
    FIGUEIRENSE("Figueirense FC"),
    FULHAM("Fulham FC"),
    GALATASARAY("Galatasaray FC"),
    GENK("Genk FC"),
    GENOA("Genoa CFC"),
    GODOY("Godoy Cruz FC"),
    GOZTEPE("Goztepe FC"),
    GRASSHOPPERS("Grasshoppers FC"),
    GREMIO("Gremio Football Porto"),
    GUINGAMP("Guingamp FC"),
    GYMBARGAY("Gym Bar Gay League FC"),
    HAMBURGER("Hamburger SV"),
    HANNOVER("Hanover 96"),
    MIDLOTHIAN("Heart of Midlothian FC"),
    HELLAS("Hellas Verona FC"),
    HERACLES("Heracles Almelo FC"),
    HERTHA("Hertha BSC"),
    HIBERNIAN("Hibernian FC"),
    HUDDERSFIELD("Huddersfield Town FC"),
    HULL("Hull City FC"),
    HURACAN("Huracan FC"),
    INDEPENDIENTE("Independiente FC"),
    INTER("Inter Milan"),
    INVERNESS("Inverness Caledonian Thistle FC"),
    IPSWICH("Ipswich Town FC"),
    ISTANBUL("Istanbul Basaksehir FC"),
    JUVENTUS("Juventus"),
    GENT("Kaa Gent FC"),
    KAYSERISPOR("Kayserispor FC"),
    KILMARNOCK("Kilmarnock FC"),
    KORTRJIK("Kortrjik FC"),
    GALAXY("LA Galaxy FC"),
    GIANTSGAY("LA Giants Gay League FC"),
    LAUSANNE("Lausanne FC"),
    LEEDS("Leeds United FC"),
    LEICESTER("Leicester City FC"),
    LIEGE("Liege FC"),
    LIVERPOOL("Liverpool FC"),
    LOKEREN("Lokeren FC"),
    LOKOMOTIV("Lokomotiv Moscow"),
    LONDONGAY("London Gay League FC"),
    LOSANGELES("Los Angeles FC"),
    LUGANO("Lugano FC"),
    LUZERN("Luzern FC"),
    CITY("Manchester City FC"),
    UNITED("Manchester United FC"),
    MARSEILLE("Marseille FC"),
    MIDDLESBROUGH("Middlesbrough FC"),
    MILWALL("Milwall FC"),
    MINNESOTA("Minnesota United FC"),
    MONACO("Monaco FC"),
    MONTPELLIER("Montpellier FC"),
    MONTREAL("Montreal United"),
    MOTHERWELL("Motherwell FC"),
    NANTES("Nantes FC"),
    NEWENGLAND("New England Revolution"),
    NEWYORK("New York City"),
    NEWYORKGAY("New York Gay League FC"),
    NEWCASTLE("Newcastle United FC"),
    NORWICH("Norwich City FC"),
    NOTTINGHAM("Nottingham Forest FC"),
    NICE("OGC Nice FC"),
    LYON("Olympique Lyonnais"),
    PSG("Paris St Germain"),
    PATRICK("Partick Thistle FC"),
    ZWOLLE("PEC Zwolle"),
    PHILADELPHIA("Philadelphia Union"),
    PORTLAND("Portland Timbers FC"),
    PRESTON("Preston FC"),
    PSV("PSV Eindhoven"),
    EXCEL("R Excel Mouscron FC"),
    RACING("Racing Club FC"),
    LEIPZIG("RB Leipzig"),
    READING("Reading FC"),
    REAL("Real Madrid"),
    SALTLAKE("Real Salt Lake"),
    RENNES("Rennes FC"),
    RIOAVE("Rio Ave FC"),
    ROCHESTERGAY("Rochester Gay League FC"),
    ROSSCOUNTY("Ross County FC"),
    RUBIN("Rubin Kazan"),
    BRAGA("SC Braga"),
    BENFICA("SL Benfica"),
    NAPOLI("SSC Napoli"),
    SANLORENZO("San Lorenzo FC"),
    SANMARTIN("San Martin FC"),
    SANTOS("Santos FC"),
    SAOPAULO("Sao Paulo FC"),
    HEERENVEEN("SC Heerenveen FC"),
    SHEFFIELD("Sheffield United FC"),
    TRUIDEN("Sint-Truiden FC"),
    SION("Sion FC"),
    SIVASSPOR("Sivasspor FC"),
    SKA("SKA-Khabarovsk"),
    SOUTHAMPTON("Southampton FC"),
    SPARTAK("Spartak Moskva FC"),
    CORINTHIANS("Sport Club Corinthians"),
    RECIFE("Sport Club do Recife"),
    INTERNACIONAL("Sport Club Internacional"),
    SPORTING("Sporting CP"),
    LAZIO("SS Lazio"),
    JOHNSTONE("St Johnstone FC"),
    MIRREN("St Mirren FC"),
    STOKE("Stoke City FC"),
    SUNDERLAND("Sunderland FC"),
    WERDER("SV Werder Bremen"),
    SWANSEA("Swansea City FC"),
    TALLERES("Talleres Cordoba"),
    TEREK("Terek Grozny"),
    TORINO("Torino FC"),
    TOSNO("Tosno"),
    TOTTENHAM("Tottenham Hotspur FC"),
    TOULOUSE("Toulouse FC"),
    TRABZONSPOR("Trabzonspor FC"),
    SAMPDORIA("UC Sampdoria"),
    UDINESE("Udinese Calcio"),
    UNION("Union FC"),
    UTAHGAY("Utah Gay League FC"),
    STUTTGART("VfB Stuttgart"),
    WOLFSBURG("VfL Wolfsburg"),
    VITESSE("Vitesse FC"),
    VITORIA("Vitoria FC"),
    VVV("VVV Venlo"),
    WAASLAND("Waasland-Bevern FC"),
    WATFORD("Watford FC"),
    WBA("West Bromwhich Albion FC"),
    WESTHAM("West Ham United FC"),
    WOLVES("Wolves FC"),
    WMILAN("Women's AC Milan"),
    WARSENAL("Women's Arsenal FC"),
    WBAYERN("Women's Bayern Munich"),
    WCHELSEA("Women's Chelsea FC"),
    WBARCELONA("Women's FC Barcelona"),
    WHOTSPUR("Women's Hostpur FC"),
    WLANCASHIRE("Women's Lancashire Thunders FC"),
    WLOUGH("Women's Loughborough Lightning FC"),
    WMUTD("Women's Manchester United FC"),
    WSOUTHAMPTON("Women's Southampton FC"),
    WSOUTHERN("Women's Southern Vipers FC"),
    WSURREY("Women's Surrey Stars FC"),
    WWESTERN("Women's Western Storm FC"),
    WYORKSHIRE("Women's Yorkshire Diamonds FC"),
    YOUNGBOYS("Young Boys"),
    ZENIT("Zenit FC");


    public final String teamName;

    Team(String name) {
        this.teamName = name;
    }
}
